services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "16G"
      USERNAME: "nim"
      PASSWORD: "nim"
      KEYBOARD: "fr-FR"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006/tcp
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
      - ./bin:/data
      - ./win11.iso:/boot.iso
    restart: always
    stop_grace_period: 2m